# Site settings
title: MSAI 349 - Alzheimer's
email: ikhlas.attarwala@gmail.com; jaieu.sheil@gmail.com; jackwilliamrichard@gmail.com; quinciahu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ikhlas attarwala is a graduate student in artificial intelligence at Northwestern University interested in Machine Learning and Computer Vision.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  Ikhlas-Attarwala


# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com


# Build settings
markdown: kramdown
